### ISSUE TITLE
shell.nix appears to make a nixops that doesn't list any plugins?

### ISSUE THREAD

**Issue by lf-** [nix-community/nixops-digitalocean#7]
On a fresh clone (fe855bf61adea5ae95ecf8a5f9b0b25dccaec6a3) of the repository, I did this:

```
dev/nixops-digitalocean - [master] » nix-shell

[nix-shell:~/dev/nixops-digitalocean]$ nixops list-plugins
+-------------------+
| Installed Plugins |
+-------------------+
+-------------------+
```

This appears incorrect; should there not be a plugin there? I could have also made an error in setting up my environment as I had trouble finding documentation for either how NixOps handles plugin installation in general or how this plugin handles it.

**Comment by Kiwi** [comment]
it doesn't actually make a nixops you have to use poetry. i updated the documentation in a branch i was working on https://github.com/Kiwi/nixops-digitalocean/tree/no-kitchen-sink

**Comment by Kiwi** [comment]
[should be good to go now](https://github.com/nix-community/nixops-digitalocean/blob/b527b4bd27a419753e38c8231fd7528b3ea33886/shell.nix#L15-L18)

```
19:33:48 [kiwi@mvp-nixos nixops-digitalocean]$ nix-shell --pure --run "nixops list-plugins"
+-------------------+
| Installed Plugins |
+-------------------+
|    digitalocean   |
+-------------------+
19:34:06 [kiwi@mvp-nixos nixops-digitalocean]$
```
